### ISSUE TITLE
Cannot reproduce the performance in the paper

### ISSUE THREAD

**Issue by YangRui2015** [henrycharlesworth/PlanGAN#1]
Hi, 
I really appreciate your exciting work PlanGAN and I have been trying to reproduce the results in the last two weeks (it takes a long time to run). However, the results using the parameters in the paper cannot match the results reported in the paper. I wonder if the version of the code is not the one you used in the experiments. Can you check the code and the parameters?

Best regards,

<img width="1146" alt="截屏2021-12-29 下午10 30 45" src="https://user-images.githubusercontent.com/38036768/147672559-6d8af359-5951-4fce-a60b-305a5bea7848.png">
 

The configuration I used is as follows:
> parser.add_argument('--expt_name', type=str, default="")
parser.add_argument('--env', type=str, default="fetch_pick_and_place")
parser.add_argument('--tau', type=int, default=5)
#data collection
parser.add_argument('--traj_len', type=int, default=50)
parser.add_argument('--init_rand_trajs', type=int, default=250) 
parser.add_argument('--filter_rand_trajs', dest='filter_rand_trajs', action='store_true')
parser.add_argument('--extra_trajs', type=int, default=3000)
parser.add_argument('--min_traj_len', type=int, default=20)
parser.add_argument('--exploration_noise', type=float, default=0.2)
parser.add_argument('--buffer_capacity', type=int, default=1000000)
#networks
parser.add_argument('--OSM_hidden_sizes', type=str, default="512,512")
parser.add_argument('--G_hidden_sizes', type=str, default="512,512")
parser.add_argument('--D_hidden_sizes', type=str, default="512,512")
#GAN/one-step model training
parser.add_argument('--reg_gan_with_osm', dest='reg_gan_with_osm', action='store_true')
parser.add_argument('--gan_model_l2', type=float, default=30.0)
parser.add_argument('--gan_latent_dim', type=int, default=64)
parser.add_argument('--l2_G', type=float, default=0.0001)
parser.add_argument('--l2_D', type=float, default=0.0001)
parser.add_argument('--l2_OSM', type=float, default=0.0001)
parser.add_argument('--G_optimiser', type=str, default="ADAM 0.0001 0.5 0.999")
parser.add_argument('--D_optimiser', type=str, default="ADAM 0.0001 0.5 0.999")
parser.add_argument('--OSM_optimiser', type=str, default="ADAM 0.001 0.9 0.999")
parser.add_argument('--init_gan_train_its', type=int, default=100000)
parser.add_argument('--init_osm_train_its', type=int, default=100000) 
parser.add_argument('--train_per_extra_gan', type=int, default=250) 
parser.add_argument('--train_per_extra_osm', type=int, default=250)
parser.add_argument('--gan_batch_size', type=int, default=128)
parser.add_argument('--osm_batch_size', type=int, default=256)
parser.add_argument('--big_trains_at', type=str, default="")
parser.add_argument('--filter_train_batch', dest='filter_train_batch', action='store_true')
parser.add_argument('--random_future_goals', dest='random_future_goals', action='store_true')
parser.add_argument('--num_gans', type=int, default=3)
parser.add_argument('--num_osms', type=int, default=3)
parser.add_argument('--use_all_osms_for_each_gan', dest='use_all_osms_for_each_gan', action='store_true')
#planner
parser.add_argument('--plan_num_init_acs', type=int, default=25) 
parser.add_argument('--plan_alpha', type=float, default=5.0)
parser.add_argument('--plan_average_ac', dest='plan_av_ac', action='store_true')
parser.add_argument('--plan_num_copies', type=int, default=100)  
parser.add_argument('--planner_osm_frac', type=float, default=0.5)
#just train on random trajs:
parser.add_argument('--no_extra_trajs', dest='run_extra_trajs', action='store_false')
#eval 
parser.add_argument('--eval_every', type=int, default=5000) 
parser.add_argument('--eval_trajs', type=int, default=50)  
parser.add_argument('--print_every', type=int, default=50) 
parser.add_argument('--log_path', type=str, default='experiments')

**Comment by henrycharlesworth** [comment]
Hi! It's been a long time since I've looked at the code so my memory of how all the details work is not as fresh as it was when I did the work. That definitely doesn't look good though - it's possible I've messed up the default hyperparameters in this code repo (I do remember that particularly for the pick and place environment the method was a quite sensitive to hyperparameter choices).

Do the prerun models work for you? If you look here: https://github.com/henrycharlesworth/PlanGAN/blob/master/experiments/FetchPickAndPlace/experiment_args.json this SHOULD be a copy of the exact set of hyperparameters used to train the prerun model for FetchPickAndPlace. It does look like there are a few differences between those and the default ones included in this repo, so maybe you could try again with those?

The other thing I'd say is maybe try and reproduce the FetchPush results first, because I think the method was generally more robust on that environment (the hyperparameters used for that are here: https://github.com/henrycharlesworth/PlanGAN/blob/master/experiments/FetchPush/experiment_args.json)

**Comment by YangRui2015** [comment]
Thank you so much for your helpful tips! Using the parameters in the json files, I reproduced the results as follows:
<img width="890" alt="截屏2022-01-04 上午11 26 20" src="https://user-images.githubusercontent.com/38036768/148005655-829794a0-c653-4145-9c4c-eaf79bdd185a.png">

I got the previous results because I used several different parameters as default such as 'filter_rand_trajs'.
